<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputPath>..\..\1.6\Assemblies</OutputPath>
    <TargetFramework>net48</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <DebugType>None</DebugType>
    <LangVersion>latest</LangVersion>
    <FileVersion>1.6.2</FileVersion>
    <Copyright>© BookBurner 2026 - MIT License</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref">
      <Version>*</Version>
      <ExcludeAssets>runtime</ExcludeAssets>
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>